
linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    enable:
      - fieldalignment
      - shadow
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - bodyclose
#    - unused # intentionally commented to avoid unused func warning as this repo is library
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc # pre-allocate slices with define size if the slice size is known in advance
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - whitespace
    - lll
    - wsl # While space linter

run:
  issues-exit-code: 1
  go: '1.22'
#  skip-dirs:
#    - sample
#  skip-files:
#    - sample

issues:
  exclude-rules:
    - path: info/as_parser_test\.go
      linters:
      - lll # Test code is allowed to have long lines
    - path: asconfig/generate_test\.go
      linters:
      - dupl # Test code is allowed to have duplicate code
    - path: asconfig/asconfig_test\.go
      linters:
      - dupl # Test code is allowed to have duplicate code
    - path: '(.+)test\.go'
      linters:
      - govet # Test code field alignment for sake of space is not a concern
    - linters:
        - lll
      source: "// "
