package asconfig

import (
	"testing"

	lib "github.com/aerospike/aerospike-management-lib"
	"github.com/go-logr/logr"
	"github.com/golang/mock/gomock"
	"github.com/stretchr/testify/suite"
)

type GenerateTestSuite struct {
	suite.Suite
	mockGetter *MockConfGetter
	// asinfo *AsInfo
	ctrl *gomock.Controller
}

func (suite *GenerateTestSuite) SetupTest() {
	suite.ctrl = gomock.NewController(suite.T())
	suite.mockGetter = NewMockConfGetter(suite.ctrl)
	// mockConnFact := NewMockconnectionFactory(suite.ctrl)
	// suite.mockConn = NewMockconnection(suite.ctrl)
	// policy := &aero.ClientPolicy{}
	// host := &aero.Host{}
	// mockConnFact.EXPECT().NewConnection(policy, host).Return(suite.mockConn, nil).AnyTimes()
	// suite.mockConn.EXPECT().IsConnected().Return(true).AnyTimes()
	// suite.mockConn.EXPECT().Login(policy).Return(nil).AnyTimes()
	// suite.mockConn.EXPECT().SetTimeout(gomock.Any(), time.Second*100).AnyTimes()
	// suite.mockConn.EXPECT().Close().Return().AnyTimes()
	// suite.asinfo = NewAsInfoWithConnFactory(logr.Discard(), host, policy, mockConnFact)
}

func (suite *GenerateTestSuite) TestGenerate() {
	testCases := []struct {
		name       string
		allConfigs Conf
		metadata   Conf
		expected   Conf
	}{
		// Add more test cases here
		{
			"name",
			Conf{
				"config": Conf{
					"logging": Conf{
						"/var/log/aerospike/aerospike.log": Conf{
							"aggr":         "INFO",
							"alloc":        "INFO",
							"appeal":       "INFO",
							"arenax":       "INFO",
							"as":           "INFO",
							"audit":        "INFO",
							"batch":        "INFO",
							"batch-sub":    "INFO",
							"bin":          "INFO",
							"clustering":   "INFO",
							"config":       "INFO",
							"drv_pmem":     "INFO",
							"drv_ssd":      "INFO",
							"exchange":     "INFO",
							"exp":          "INFO",
							"fabric":       "INFO",
							"flat":         "INFO",
							"geo":          "INFO",
							"hardware":     "INFO",
							"hb":           "INFO",
							"health":       "INFO",
							"hlc":          "INFO",
							"index":        "INFO",
							"info":         "INFO",
							"info-port":    "INFO",
							"key-busy":     "INFO",
							"migrate":      "INFO",
							"misc":         "INFO",
							"msg":          "INFO",
							"namespace":    "INFO",
							"nsup":         "INFO",
							"os":           "INFO",
							"particle":     "INFO",
							"partition":    "INFO",
							"proto":        "INFO",
							"proxy":        "INFO",
							"proxy-divert": "INFO",
							"query":        "INFO",
							"record":       "INFO",
							"roster":       "INFO",
							"rw":           "INFO",
							"rw-client":    "INFO",
							"secrets":      "INFO",
							"security":     "INFO",
							"service":      "INFO",
							"service-list": "INFO",
							"sindex":       "INFO",
							"skew":         "INFO",
							"smd":          "INFO",
							"socket":       "INFO",
							"storage":      "INFO",
							"tls":          "INFO",
							"truncate":     "INFO",
							"tsvc":         "INFO",
							"udf":          "INFO",
							"vault":        "INFO",
							"vmapx":        "INFO",
							"xdr":          "INFO",
							"xdr-client":   "INFO",
							"xmem":         "INFO",
						},
						"stderr": Conf{
							"aggr":         "INFO",
							"alloc":        "INFO",
							"appeal":       "INFO",
							"arenax":       "INFO",
							"as":           "INFO",
							"audit":        "INFO",
							"batch":        "INFO",
							"batch-sub":    "INFO",
							"bin":          "INFO",
							"clustering":   "INFO",
							"config":       "INFO",
							"drv_pmem":     "INFO",
							"drv_ssd":      "INFO",
							"exchange":     "INFO",
							"exp":          "INFO",
							"fabric":       "INFO",
							"flat":         "INFO",
							"geo":          "INFO",
							"hardware":     "INFO",
							"hb":           "INFO",
							"health":       "INFO",
							"hlc":          "INFO",
							"index":        "INFO",
							"info":         "INFO",
							"info-port":    "INFO",
							"key-busy":     "INFO",
							"migrate":      "INFO",
							"misc":         "INFO",
							"msg":          "INFO",
							"namespace":    "INFO",
							"nsup":         "INFO",
							"os":           "INFO",
							"particle":     "INFO",
							"partition":    "INFO",
							"proto":        "INFO",
							"proxy":        "INFO",
							"proxy-divert": "INFO",
							"query":        "INFO",
							"record":       "INFO",
							"roster":       "INFO",
							"rw":           "INFO",
							"rw-client":    "INFO",
							"secrets":      "INFO",
							"security":     "INFO",
							"service":      "INFO",
							"service-list": "INFO",
							"sindex":       "INFO",
							"skew":         "INFO",
							"smd":          "INFO",
							"socket":       "INFO",
							"storage":      "INFO",
							"tls":          "INFO",
							"truncate":     "INFO",
							"tsvc":         "INFO",
							"udf":          "INFO",
							"vault":        "INFO",
							"vmapx":        "INFO",
							"xdr":          "INFO",
							"xdr-client":   "INFO",
							"xmem":         "INFO",
						},
					},
					"namespaces": Conf{
						"bar": Conf{
							"allow-ttl-without-nsup":                 false,
							"background-query-max-rps":               10000,
							"conflict-resolution-policy":             "generation",
							"conflict-resolve-writes":                false,
							"default-ttl":                            0,
							"disable-cold-start-eviction":            false,
							"disable-write-dup-res":                  false,
							"disallow-expunge":                       false,
							"disallow-null-setname":                  false,
							"enable-benchmarks-batch-sub":            false,
							"enable-benchmarks-ops-sub":              false,
							"enable-benchmarks-read":                 false,
							"enable-benchmarks-udf":                  false,
							"enable-benchmarks-udf-sub":              false,
							"enable-benchmarks-write":                false,
							"enable-hist-proxy":                      false,
							"evict-hist-buckets":                     10000,
							"evict-tenths-pct":                       5,
							"force-long-queries":                     false,
							"geo2dsphere-within.earth-radius-meters": 6371000,
							"geo2dsphere-within.level-mod":           1,
							"geo2dsphere-within.max-cells":           12,
							"geo2dsphere-within.max-level":           20,
							"geo2dsphere-within.min-level":           1,
							"geo2dsphere-within.strict":              true,
							"high-water-disk-pct":                    0,
							"high-water-memory-pct":                  0,
							"ignore-migrate-fill-delay":              false,
							"index-stage-size":                       1073741824,
							"index-type":                             "shmem",
							"inline-short-queries":                   false,
							"max-record-size":                        0,
							"memory-size":                            1073741824,
							"migrate-order":                          5,
							"migrate-retransmit-ms":                  5000,
							"migrate-sleep":                          1,
							"nsup-hist-period":                       3600,
							"nsup-period":                            0,
							"nsup-threads":                           1,
							"partition-tree-sprigs":                  256,
							"prefer-uniform-balance":                 true,
							"rack-id":                                0,
							"read-consistency-level-override":        "off",
							"reject-non-xdr-writes":                  false,
							"reject-xdr-writes":                      false,
							"replication-factor":                     1,
							"sets": Conf{
								"testset": Conf{
									"disable-eviction":  false,
									"enable-index":      false,
									"stop-writes-count": 0,
									"stop-writes-size":  0,
								},
							},
							"sindex-stage-size":                1073741824,
							"sindex-type":                      "shmem",
							"single-query-threads":             4,
							"stop-writes-pct":                  90,
							"stop-writes-sys-memory-pct":       90,
							"storage-engine":                   "memory",
							"strong-consistency":               false,
							"strong-consistency-allow-expunge": false,
							"tomb-raider-eligible-age":         86400,
							"tomb-raider-period":               86400,
							"transaction-pending-limit":        20,
							"truncate-threads":                 4,
							"write-commit-level-override":      "off",
							"xdr-bin-tombstone-ttl":            86400,
							"xdr-tomb-raider-period":           120,
							"xdr-tomb-raider-threads":          1,
						},
						"test": Conf{
							"allow-ttl-without-nsup":                 false,
							"background-query-max-rps":               10000,
							"conflict-resolution-policy":             "generation",
							"conflict-resolve-writes":                false,
							"default-ttl":                            0,
							"disable-cold-start-eviction":            false,
							"disable-write-dup-res":                  false,
							"disallow-expunge":                       false,
							"disallow-null-setname":                  false,
							"enable-benchmarks-batch-sub":            false,
							"enable-benchmarks-ops-sub":              false,
							"enable-benchmarks-read":                 false,
							"enable-benchmarks-udf":                  false,
							"enable-benchmarks-udf-sub":              false,
							"enable-benchmarks-write":                false,
							"enable-hist-proxy":                      false,
							"evict-hist-buckets":                     10000,
							"evict-tenths-pct":                       5,
							"force-long-queries":                     false,
							"geo2dsphere-within.earth-radius-meters": 6371000,
							"geo2dsphere-within.level-mod":           1,
							"geo2dsphere-within.max-cells":           15,
							"geo2dsphere-within.max-level":           20,
							"geo2dsphere-within.min-level":           1,
							"geo2dsphere-within.strict":              true,
							"high-water-disk-pct":                    0,
							"high-water-memory-pct":                  0,
							"ignore-migrate-fill-delay":              false,
							"index-stage-size":                       1073741824,
							"index-type":                             "shmem",
							"inline-short-queries":                   false,
							"max-record-size":                        0,
							"memory-size":                            536870912,
							"migrate-order":                          5,
							"migrate-retransmit-ms":                  5000,
							"migrate-sleep":                          1,
							"nsup-hist-period":                       3600,
							"nsup-period":                            0,
							"nsup-threads":                           1,
							"partition-tree-sprigs":                  256,
							"prefer-uniform-balance":                 true,
							"rack-id":                                0,
							"read-consistency-level-override":        "off",
							"reject-non-xdr-writes":                  false,
							"reject-xdr-writes":                      false,
							"replication-factor":                     1,
							"sets": Conf{
								"testset": Conf{
									"disable-eviction":  false,
									"enable-index":      false,
									"stop-writes-count": 0,
									"stop-writes-size":  0,
								},
							},
							"sindex-stage-size":                1073741824,
							"sindex-type":                      "shmem",
							"single-query-threads":             4,
							"stop-writes-pct":                  90,
							"stop-writes-sys-memory-pct":       90,
							"storage-engine":                   "memory",
							"strong-consistency":               false,
							"strong-consistency-allow-expunge": false,
							"tomb-raider-eligible-age":         86400,
							"tomb-raider-period":               86400,
							"transaction-pending-limit":        20,
							"truncate-threads":                 4,
							"write-commit-level-override":      "off",
							"xdr-bin-tombstone-ttl":            86400,
							"xdr-tomb-raider-period":           120,
							"xdr-tomb-raider-threads":          1,
						},
					},
					"network": Conf{
						"fabric.channel-bulk-fds":           2,
						"fabric.channel-bulk-recv-threads":  4,
						"fabric.channel-ctrl-fds":           1,
						"fabric.channel-ctrl-recv-threads":  4,
						"fabric.channel-meta-fds":           1,
						"fabric.channel-meta-recv-threads":  4,
						"fabric.channel-rw-fds":             8,
						"fabric.channel-rw-recv-pools":      1,
						"fabric.channel-rw-recv-threads":    16,
						"fabric.keepalive-enabled":          true,
						"fabric.keepalive-intvl":            1,
						"fabric.keepalive-probes":           10,
						"fabric.keepalive-time":             1,
						"fabric.latency-max-ms":             5,
						"fabric.port":                       3001,
						"fabric.recv-rearm-threshold":       1024,
						"fabric.send-threads":               8,
						"fabric.tls-name":                   "null",
						"fabric.tls-port":                   0,
						"heartbeat.connect-timeout-ms":      500,
						"heartbeat.interval":                150,
						"heartbeat.mode":                    "multicast",
						"heartbeat.mtu":                     65535,
						"heartbeat.multicast-group":         "239.1.99.223",
						"heartbeat.multicast-ttl":           0,
						"heartbeat.port":                    9918,
						"heartbeat.protocol":                "v3",
						"heartbeat.timeout":                 10,
						"info.port":                         3003,
						"service.access-port":               0,
						"service.address":                   "any",
						"service.alternate-access-port":     0,
						"service.disable-localhost":         false,
						"service.port":                      3000,
						"service.tls-access-port":           0,
						"service.tls-alternate-access-port": 0,
						"service.tls-name":                  "null",
						"service.tls-port":                  0,
					},
					"racks": []lib.Stats{
						{
							"ns":     "test",
							"rack_0": "BB9030011AC4202",
						},
						{
							"ns":     "bar",
							"rack_0": "BB9030011AC4202",
						},
					},
					"service": Conf{
						"advertise-ipv6":              false,
						"auto-pin":                    "none",
						"batch-index-threads":         8,
						"batch-max-buffers-per-queue": 255,
						"batch-max-unused-buffers":    256,
						"cluster-name":                "7.x-cluster",
						"debug-allocations":           "none",
						"disable-udf-execution":       false,
						"downgrading":                 false,
						"enable-benchmarks-fabric":    false,
						"enable-health-check":         false,
						"enable-hist-info":            false,
						"enforce-best-practices":      false,
						"feature-key-file[0]":         "/etc/aerospike/features.conf",
						"indent-allocations":          false,
						"info-max-ms":                 10000,
						"info-threads":                16,
						"keep-caps-ssd-health":        false,
						"log-local-time":              false,
						"log-millis":                  false,
						"microsecond-histograms":      false,
						"migrate-fill-delay":          0,
						"migrate-max-num-incoming":    4,
						"migrate-threads":             1,
						"min-cluster-size":            1,
						"node-id":                     "BB9030011AC4202",
						"node-id-interface":           "null",
						"os-group-perms":              false,
						"pidfile":                     "null",
						"proto-fd-idle-ms":            0,
						"proto-fd-max":                15000,
						"query-max-done":              100,
						"query-threads-limit":         128,
						"run-as-daemon":               true,
						"salt-allocations":            false,
						"secrets-address-port":        "null",
						"secrets-tls-context":         "null",
						"service-threads":             8,
						"sindex-builder-threads":      4,
						"sindex-gc-period":            10,
						"stay-quiesced":               false,
						"ticker-interval":             10,
						"transaction-max-ms":          1000,
						"transaction-retry-ms":        1002,
						"vault-ca":                    "null",
						"vault-namespace":             "null",
						"vault-path":                  "null",
						"vault-token-file":            "null",
						"vault-url":                   "null",
						"work-directory":              "/opt/aerospike",
					},
					"xdr": Conf{
						"dcs": Conf{
							"DC1": Conf{
								"auth-mode":                  "none",
								"auth-password-file":         "null",
								"auth-user":                  "null",
								"connector":                  false,
								"max-recoveries-interleaved": 0,
								"namespaces": Conf{
									"test": Conf{
										"bin-policy":               "all",
										"compression-level":        1,
										"compression-threshold":    128,
										"delay-ms":                 0,
										"enable-compression":       false,
										"enabled":                  true,
										"forward":                  false,
										"hot-key-ms":               100,
										"ignore-expunges":          false,
										"ignored-bins":             "",
										"ignored-sets":             "",
										"max-throughput":           100000,
										"remote-namespace":         "null",
										"sc-replication-wait-ms":   100,
										"ship-bin-luts":            false,
										"ship-nsup-deletes":        false,
										"ship-only-specified-sets": false,
										"shipped-bins":             "",
										"shipped-sets":             "",
										"transaction-queue-limit":  16384,
										"write-policy":             "auto",
									},
								},
								"node-address-port":            "",
								"period-ms":                    100,
								"tls-name":                     "null",
								"use-alternate-access-address": false,
							},
							"DC2": Conf{
								"auth-mode":                  "none",
								"auth-password-file":         "null",
								"auth-user":                  "null",
								"connector":                  false,
								"max-recoveries-interleaved": 0,
								"namespaces": Conf{
									"bar": Conf{
										"bin-policy":               "all",
										"compression-level":        1,
										"compression-threshold":    128,
										"delay-ms":                 0,
										"enable-compression":       false,
										"enabled":                  true,
										"forward":                  false,
										"hot-key-ms":               100,
										"ignore-expunges":          false,
										"ignored-bins":             "",
										"ignored-sets":             "",
										"max-throughput":           100000,
										"remote-namespace":         "null",
										"sc-replication-wait-ms":   100,
										"ship-bin-luts":            false,
										"ship-nsup-deletes":        false,
										"ship-only-specified-sets": false,
										"shipped-bins":             "",
										"shipped-sets":             "",
										"transaction-queue-limit":  16384,
										"write-policy":             "auto",
									},
								},
								"node-address-port":            "",
								"period-ms":                    100,
								"tls-name":                     "null",
								"use-alternate-access-address": false,
							},
						},
						"src-id":       0,
						"trace-sample": 0,
					},
				},
			},
			Conf{"metadata": Conf{"build": "7.0.0"}},
			nil,
		},
	}

	for _, tc := range testCases {
		suite.Run(tc.name, func() {
			suite.mockGetter.EXPECT().AllConfigs().Return(tc.allConfigs, nil)
			suite.mockGetter.EXPECT().GetAsInfo("metadata").Return(tc.metadata, nil)

			actual, err := GenerateConf(logr.Discard(), suite.mockGetter)

			suite.Assert().Nil(err)
			suite.Assert().Equal(tc.expected, actual)
		})
	}
}

func TestGenerateTestSuiteSuite(t *testing.T) {
	suite.Run(t, new(GenerateTestSuite))
}
