package asconfig

import (
	"log"
	"os"
	"testing"

	"github.com/go-logr/logr"
	"github.com/stretchr/testify/suite"
	"go.uber.org/mock/gomock"
)

type GenerateUnitTestSuite struct {
	suite.Suite
	mockGetter *MockConfGetter
	// asinfo *AsInfo
	ctrl *gomock.Controller
}

func (s *GenerateUnitTestSuite) SetupSuite() {
	schemaDir := os.Getenv("TEST_SCHEMA_DIR")

	if schemaDir == "" {
		log.Printf("Env var TEST_SCHEMA_DIR must be set.")
		s.T().Fail()
	}

	err := Init(logr.Discard(), schemaDir)
	if err != nil {
		s.T().Fatal(err)
	}
}

func (s *GenerateUnitTestSuite) SetupTest() {
	s.ctrl = gomock.NewController(s.T())
	s.mockGetter = NewMockConfGetter(s.ctrl)
}

type GenerateTC struct {
	name           string
	removeDefaults bool
	allConfigs     Conf
	metadata       Conf
	expected       Conf
}

func convertIntToInt64(conf Conf) Conf {
	for key, value := range conf {
		switch v := value.(type) {
		case int:
			conf[key] = int64(v)
		case Conf:
			conf[key] = convertIntToInt64(v)
		case []Conf:
			for i, c := range v {
				v[i] = convertIntToInt64(c)
			}
		}
	}

	return conf
}

func (s *GenerateUnitTestSuite) TestGenerate() {
	testCases := []GenerateTC{
		loggingTC,
		namespaceTC,
		networkTC,
		serviceTC,
		securityEnabled57TC,
		securityDisabled57TC,
		securityEnabled56TC,
		securityDisabled56TC,
		xdrTC,
		loggingDefaultsTC,
		namespacesDefaultsTC,
		networkDefaultsTC,
		serviceDefaultsTC,
		security57DefaultsTC,
		security57AllDefaultsTC,
		xdrDefaultsTC,
		shadowDeviceIssueTC,
	}

	for _, tc := range testCases {
		s.Run(tc.name, func() {
			s.mockGetter.EXPECT().AllConfigs().Return(convertIntToInt64(tc.allConfigs), nil)
			s.mockGetter.EXPECT().GetAsInfo("metadata").Return(tc.metadata, nil)

			logger := logr.Discard()
			expected := newGenConf(
				convertIntToInt64(tc.expected),
				tc.metadata["metadata"].(Conf)["asd_build"].(string),
			)

			actual, err := GenerateConf(logger, s.mockGetter, tc.removeDefaults)

			s.Assert().Nil(err)
			s.Assert().Equal(expected, actual)
		})
	}
}

func TestGenerateTestSuiteSuite(t *testing.T) {
	suite.Run(t, new(GenerateUnitTestSuite))
}

var loggingTC = GenerateTC{
	"logging",
	false,
	Conf{
		"logging": Conf{
			"/var/log/aerospike/aerospike.log": Conf{
				"aggr":         "INFO",
				"alloc":        "INFO",
				"appeal":       "INFO",
				"arenax":       "INFO",
				"as":           "INFO",
				"audit":        "INFO",
				"batch":        "INFO",
				"batch-sub":    "INFO",
				"bin":          "INFO",
				"clustering":   "INFO",
				"config":       "INFO",
				"drv_pmem":     "INFO",
				"drv_ssd":      "INFO",
				"exchange":     "INFO",
				"exp":          "INFO",
				"fabric":       "INFO",
				"flat":         "INFO",
				"geo":          "INFO",
				"hardware":     "INFO",
				"hb":           "INFO",
				"health":       "INFO",
				"hlc":          "INFO",
				"index":        "INFO",
				"info":         "INFO",
				"info-port":    "INFO",
				"key-busy":     "INFO",
				"migrate":      "INFO",
				"misc":         "INFO",
				"msg":          "INFO",
				"namespace":    "INFO",
				"nsup":         "INFO",
				"os":           "INFO",
				"particle":     "INFO",
				"partition":    "INFO",
				"proto":        "INFO",
				"proxy":        "INFO",
				"proxy-divert": "INFO",
				"query":        "INFO",
				"record":       "INFO",
				"roster":       "INFO",
				"rw":           "INFO",
				"rw-client":    "INFO",
				"secrets":      "INFO",
				"security":     "INFO",
				"service":      "INFO",
				"service-list": "INFO",
				"sindex":       "INFO",
				"skew":         "INFO",
				"smd":          "INFO",
				"socket":       "INFO",
				"storage":      "INFO",
				"tls":          "INFO",
				"truncate":     "INFO",
				"tsvc":         "INFO",
				"udf":          "INFO",
				"vault":        "INFO",
				"vmapx":        "INFO",
				"xdr":          "INFO",
				"xdr-client":   "INFO",
				"xmem":         "INFO",
			},
			"stderr": Conf{
				"aggr":         "INFO",
				"alloc":        "INFO",
				"appeal":       "INFO",
				"arenax":       "INFO",
				"as":           "INFO",
				"audit":        "INFO",
				"batch":        "INFO",
				"batch-sub":    "INFO",
				"bin":          "INFO",
				"clustering":   "INFO",
				"config":       "INFO",
				"drv_pmem":     "INFO",
				"drv_ssd":      "INFO",
				"exchange":     "INFO",
				"exp":          "INFO",
				"fabric":       "INFO",
				"flat":         "INFO",
				"geo":          "INFO",
				"hardware":     "INFO",
				"hb":           "INFO",
				"health":       "INFO",
				"hlc":          "INFO",
				"index":        "INFO",
				"info":         "INFO",
				"info-port":    "INFO",
				"key-busy":     "INFO",
				"migrate":      "INFO",
				"misc":         "INFO",
				"msg":          "INFO",
				"namespace":    "INFO",
				"nsup":         "INFO",
				"os":           "INFO",
				"particle":     "INFO",
				"partition":    "INFO",
				"proto":        "INFO",
				"proxy":        "INFO",
				"proxy-divert": "INFO",
				"query":        "INFO",
				"record":       "INFO",
				"roster":       "INFO",
				"rw":           "INFO",
				"rw-client":    "INFO",
				"secrets":      "INFO",
				"security":     "INFO",
				"service":      "INFO",
				"service-list": "INFO",
				"sindex":       "INFO",
				"skew":         "INFO",
				"smd":          "INFO",
				"socket":       "INFO",
				"storage":      "INFO",
				"tls":          "INFO",
				"truncate":     "INFO",
				"tsvc":         "INFO",
				"udf":          "INFO",
				"vault":        "INFO",
				"vmapx":        "INFO",
				"xdr":          "INFO",
				"xdr-client":   "INFO",
				"xmem":         "INFO",
			},
			"/dev/log": Conf{
				"aggr":         "INFO",
				"alloc":        "INFO",
				"appeal":       "INFO",
				"arenax":       "INFO",
				"as":           "INFO",
				"audit":        "INFO",
				"batch":        "INFO",
				"batch-sub":    "INFO",
				"bin":          "INFO",
				"clustering":   "INFO",
				"config":       "INFO",
				"drv_pmem":     "INFO",
				"drv_ssd":      "INFO",
				"exchange":     "INFO",
				"exp":          "INFO",
				"fabric":       "INFO",
				"flat":         "INFO",
				"geo":          "INFO",
				"hardware":     "INFO",
				"hb":           "INFO",
				"health":       "INFO",
				"hlc":          "INFO",
				"index":        "INFO",
				"info":         "INFO",
				"info-port":    "INFO",
				"key-busy":     "INFO",
				"migrate":      "INFO",
				"misc":         "INFO",
				"msg":          "INFO",
				"namespace":    "INFO",
				"nsup":         "INFO",
				"os":           "INFO",
				"particle":     "INFO",
				"partition":    "INFO",
				"proto":        "INFO",
				"proxy":        "INFO",
				"proxy-divert": "INFO",
				"query":        "INFO",
				"record":       "INFO",
				"roster":       "INFO",
				"rw":           "INFO",
				"rw-client":    "INFO",
				"secrets":      "INFO",
				"security":     "INFO",
				"service":      "INFO",
				"service-list": "INFO",
				"sindex":       "INFO",
				"skew":         "INFO",
				"smd":          "INFO",
				"socket":       "INFO",
				"storage":      "INFO",
				"tls":          "INFO",
				"truncate":     "INFO",
				"tsvc":         "INFO",
				"udf":          "INFO",
				"vault":        "INFO",
				"vmapx":        "INFO",
				"xdr":          "INFO",
				"xdr-client":   "INFO",
				"xmem":         "INFO",
			},
		},
	},
	Conf{"metadata": Conf{"asd_build": "6.4.0.0", "node_id": "BB9030011AC4202"}},
	Conf{
		"logging": []Conf{
			{
				"name":         "/var/log/aerospike/aerospike.log",
				"aggr":         "INFO",
				"alloc":        "INFO",
				"appeal":       "INFO",
				"arenax":       "INFO",
				"as":           "INFO",
				"audit":        "INFO",
				"batch":        "INFO",
				"batch-sub":    "INFO",
				"bin":          "INFO",
				"clustering":   "INFO",
				"config":       "INFO",
				"drv_pmem":     "INFO",
				"drv_ssd":      "INFO",
				"exchange":     "INFO",
				"exp":          "INFO",
				"fabric":       "INFO",
				"flat":         "INFO",
				"geo":          "INFO",
				"hardware":     "INFO",
				"hb":           "INFO",
				"health":       "INFO",
				"hlc":          "INFO",
				"index":        "INFO",
				"info":         "INFO",
				"info-port":    "INFO",
				"key-busy":     "INFO",
				"migrate":      "INFO",
				"misc":         "INFO",
				"msg":          "INFO",
				"namespace":    "INFO",
				"nsup":         "INFO",
				"os":           "INFO",
				"particle":     "INFO",
				"partition":    "INFO",
				"proto":        "INFO",
				"proxy":        "INFO",
				"proxy-divert": "INFO",
				"query":        "INFO",
				"record":       "INFO",
				"roster":       "INFO",
				"rw":           "INFO",
				"rw-client":    "INFO",
				"secrets":      "INFO",
				"security":     "INFO",
				"service":      "INFO",
				"service-list": "INFO",
				"sindex":       "INFO",
				"skew":         "INFO",
				"smd":          "INFO",
				"socket":       "INFO",
				"storage":      "INFO",
				"tls":          "INFO",
				"truncate":     "INFO",
				"tsvc":         "INFO",
				"udf":          "INFO",
				"vault":        "INFO",
				"vmapx":        "INFO",
				"xdr":          "INFO",
				"xdr-client":   "INFO",
				"xmem":         "INFO",
			},
			{
				"name":         "console",
				"aggr":         "INFO",
				"alloc":        "INFO",
				"appeal":       "INFO",
				"arenax":       "INFO",
				"as":           "INFO",
				"audit":        "INFO",
				"batch":        "INFO",
				"batch-sub":    "INFO",
				"bin":          "INFO",
				"clustering":   "INFO",
				"config":       "INFO",
				"drv_pmem":     "INFO",
				"drv_ssd":      "INFO",
				"exchange":     "INFO",
				"exp":          "INFO",
				"fabric":       "INFO",
				"flat":         "INFO",
				"geo":          "INFO",
				"hardware":     "INFO",
				"hb":           "INFO",
				"health":       "INFO",
				"hlc":          "INFO",
				"index":        "INFO",
				"info":         "INFO",
				"info-port":    "INFO",
				"key-busy":     "INFO",
				"migrate":      "INFO",
				"misc":         "INFO",
				"msg":          "INFO",
				"namespace":    "INFO",
				"nsup":         "INFO",
				"os":           "INFO",
				"particle":     "INFO",
				"partition":    "INFO",
				"proto":        "INFO",
				"proxy":        "INFO",
				"proxy-divert": "INFO",
				"query":        "INFO",
				"record":       "INFO",
				"roster":       "INFO",
				"rw":           "INFO",
				"rw-client":    "INFO",
				"secrets":      "INFO",
				"security":     "INFO",
				"service":      "INFO",
				"service-list": "INFO",
				"sindex":       "INFO",
				"skew":         "INFO",
				"smd":          "INFO",
				"socket":       "INFO",
				"storage":      "INFO",
				"tls":          "INFO",
				"truncate":     "INFO",
				"tsvc":         "INFO",
				"udf":          "INFO",
				"vault":        "INFO",
				"vmapx":        "INFO",
				"xdr":          "INFO",
				"xdr-client":   "INFO",
				"xmem":         "INFO",
			},
			{
				"name":         "syslog",
				"path":         "/dev/log",
				"aggr":         "INFO",
				"alloc":        "INFO",
				"appeal":       "INFO",
				"arenax":       "INFO",
				"as":           "INFO",
				"audit":        "INFO",
				"batch":        "INFO",
				"batch-sub":    "INFO",
				"bin":          "INFO",
				"clustering":   "INFO",
				"config":       "INFO",
				"drv_pmem":     "INFO",
				"drv_ssd":      "INFO",
				"exchange":     "INFO",
				"exp":          "INFO",
				"fabric":       "INFO",
				"flat":         "INFO",
				"geo":          "INFO",
				"hardware":     "INFO",
				"hb":           "INFO",
				"health":       "INFO",
				"hlc":          "INFO",
				"index":        "INFO",
				"info":         "INFO",
				"info-port":    "INFO",
				"key-busy":     "INFO",
				"migrate":      "INFO",
				"misc":         "INFO",
				"msg":          "INFO",
				"namespace":    "INFO",
				"nsup":         "INFO",
				"os":           "INFO",
				"particle":     "INFO",
				"partition":    "INFO",
				"proto":        "INFO",
				"proxy":        "INFO",
				"proxy-divert": "INFO",
				"query":        "INFO",
				"record":       "INFO",
				"roster":       "INFO",
				"rw":           "INFO",
				"rw-client":    "INFO",
				"secrets":      "INFO",
				"security":     "INFO",
				"service":      "INFO",
				"service-list": "INFO",
				"sindex":       "INFO",
				"skew":         "INFO",
				"smd":          "INFO",
				"socket":       "INFO",
				"storage":      "INFO",
				"tls":          "INFO",
				"truncate":     "INFO",
				"tsvc":         "INFO",
				"udf":          "INFO",
				"vault":        "INFO",
				"vmapx":        "INFO",
				"xdr":          "INFO",
				"xdr-client":   "INFO",
				"xmem":         "INFO",
			},
		},
	},
}

var namespaceTC = GenerateTC{
	"namespaces",
	false,
	Conf{
		"racks": []Conf{
			{
				"ns":     "test",
				"rack_1": "BB9030011AC4202",
				"rack_0": "BB9030011AC4203",
			},
			{
				"ns":     "bar",
				"rack_2": "BB9030011AC4202",
				"rack_0": "BB9030011AC4203",
			},
		},
		"namespaces": Conf{
			"bar": Conf{
				"allow-ttl-without-nsup":                 false,
				"background-query-max-rps":               10000,
				"conflict-resolution-policy":             "generation",
				"conflict-resolve-writes":                false,
				"default-ttl":                            0,
				"disable-cold-start-eviction":            false,
				"disable-write-dup-res":                  false,
				"disallow-expunge":                       false,
				"disallow-null-setname":                  false,
				"enable-benchmarks-batch-sub":            false,
				"enable-benchmarks-ops-sub":              false,
				"enable-benchmarks-read":                 false,
				"enable-benchmarks-udf":                  false,
				"enable-benchmarks-udf-sub":              false,
				"enable-benchmarks-write":                false,
				"enable-hist-proxy":                      false,
				"evict-hist-buckets":                     10000,
				"evict-tenths-pct":                       5,
				"force-long-queries":                     false,
				"geo2dsphere-within.earth-radius-meters": 6371000,
				"geo2dsphere-within.level-mod":           1,
				"geo2dsphere-within.max-cells":           12,
				"geo2dsphere-within.max-level":           20,
				"geo2dsphere-within.min-level":           1,
				"geo2dsphere-within.strict":              true,
				"high-water-disk-pct":                    0,
				"high-water-memory-pct":                  0,
				"ignore-migrate-fill-delay":              false,
				"index-stage-size":                       1073741824,
				"index-type":                             "shmem",
				"inline-short-queries":                   false,
				"max-record-size":                        0,
				"memory-size":                            1073741824,
				"migrate-order":                          5,
				"migrate-retransmit-ms":                  5000,
				"migrate-sleep":                          1,
				"nsup-hist-period":                       3600,
				"nsup-period":                            0,
				"nsup-threads":                           1,
				"partition-tree-sprigs":                  256,
				"prefer-uniform-balance":                 true,
				"rack-id":                                0,
				"read-consistency-level-override":        "off",
				"reject-non-xdr-writes":                  false,
				"reject-xdr-writes":                      false,
				"replication-factor":                     1,
				"sets": Conf{
					"testset": Conf{
						"disable-eviction":  false,
						"enable-index":      false,
						"stop-writes-count": 0,
						"stop-writes-size":  0,
					},
				},
				"sindex-stage-size":                         1073741824,
				"sindex-type":                               "shmem",
				"single-query-threads":                      4,
				"stop-writes-pct":                           90,
				"stop-writes-sys-memory-pct":                90,
				"storage-engine":                            "device",
				"storage-engine.cache-replica-writes":       false,
				"storage-engine.cold-start-empty":           false,
				"storage-engine.commit-min-size":            0,
				"storage-engine.commit-to-device":           false,
				"storage-engine.compression":                "none",
				"storage-engine.compression-acceleration":   0,
				"storage-engine.compression-level":          0,
				"storage-engine.data-in-memory":             false,
				"storage-engine.defrag-lwm-pct":             50,
				"storage-engine.defrag-queue-min":           0,
				"storage-engine.defrag-sleep":               1000,
				"storage-engine.defrag-startup-minimum":     0,
				"storage-engine.direct-files":               false,
				"storage-engine.disable-odsync":             false,
				"storage-engine.enable-benchmarks-storage":  false,
				"storage-engine.encryption-key-file":        "null",
				"storage-engine.encryption-old-key-file":    "null",
				"storage-engine.file[0]":                    "/opt/aerospike/data/bar.dat",
				"storage-engine.file[0].shadow":             "/opt/aerospike/data/bar-shadow.dat",
				"storage-engine.file[1]":                    "/opt/aerospike/data/foo.dat",
				"storage-engine.file[1].shadow":             "/opt/aerospike/data/foo-shadow.dat",
				"storage-engine.filesize":                   1073741824,
				"storage-engine.flush-max-ms":               1000,
				"storage-engine.max-used-pct":               70,
				"storage-engine.max-write-cache":            67108864,
				"storage-engine.min-avail-pct":              5,
				"storage-engine.post-write-queue":           256,
				"storage-engine.read-page-cache":            false,
				"storage-engine.serialize-tomb-raider":      false,
				"storage-engine.sindex-startup-device-scan": false,
				"storage-engine.tomb-raider-sleep":          1000,
				"storage-engine.write-block-size":           1048576,
				"strong-consistency":                        true,
				"strong-consistency-allow-expunge":          false,
				"tomb-raider-eligible-age":                  86400,
				"tomb-raider-period":                        86400,
				"transaction-pending-limit":                 20,
				"truncate-threads":                          4,
				"write-commit-level-override":               "off",
				"xdr-bin-tombstone-ttl":                     86400,
				"xdr-tomb-raider-period":                    120,
				"xdr-tomb-raider-threads":                   1,
			},
			"test": Conf{
				"allow-ttl-without-nsup":                 false,
				"background-query-max-rps":               10000,
				"conflict-resolution-policy":             "generation",
				"conflict-resolve-writes":                false,
				"default-ttl":                            0,
				"disable-cold-start-eviction":            false,
				"disable-write-dup-res":                  false,
				"disallow-expunge":                       false,
				"disallow-null-setname":                  false,
				"enable-benchmarks-batch-sub":            false,
				"enable-benchmarks-ops-sub":              false,
				"enable-benchmarks-read":                 false,
				"enable-benchmarks-udf":                  false,
				"enable-benchmarks-udf-sub":              false,
				"enable-benchmarks-write":                false,
				"enable-hist-proxy":                      false,
				"evict-hist-buckets":                     10000,
				"evict-tenths-pct":                       5,
				"force-long-queries":                     false,
				"geo2dsphere-within.earth-radius-meters": 6371000,
				"geo2dsphere-within.level-mod":           1,
				"geo2dsphere-within.max-cells":           15,
				"geo2dsphere-within.max-level":           20,
				"geo2dsphere-within.min-level":           1,
				"geo2dsphere-within.strict":              true,
				"high-water-disk-pct":                    0,
				"high-water-memory-pct":                  0,
				"ignore-migrate-fill-delay":              false,
				"index-stage-size":                       1073741824,
				"index-type":                             "shmem",
				"inline-short-queries":                   false,
				"max-record-size":                        0,
				"memory-size":                            536870912,
				"migrate-order":                          5,
				"migrate-retransmit-ms":                  5000,
				"migrate-sleep":                          1,
				"nsup-hist-period":                       3600,
				"nsup-period":                            0,
				"nsup-threads":                           1,
				"partition-tree-sprigs":                  256,
				"prefer-uniform-balance":                 true,
				"rack-id":                                0,
				"read-consistency-level-override":        "off",
				"reject-non-xdr-writes":                  false,
				"reject-xdr-writes":                      false,
				"replication-factor":                     1,
				"sets": Conf{
					"testset": Conf{
						"disable-eviction":  false,
						"enable-index":      false,
						"stop-writes-count": 0,
						"stop-writes-size":  0,
					},
				},
				"sindex-stage-size":                1073741824,
				"sindex-type":                      "shmem",
				"single-query-threads":             4,
				"stop-writes-pct":                  90,
				"stop-writes-sys-memory-pct":       90,
				"storage-engine":                   "memory",
				"strong-consistency":               false,
				"strong-consistency-allow-expunge": false,
				"tomb-raider-eligible-age":         86400,
				"tomb-raider-period":               86400,
				"transaction-pending-limit":        20,
				"truncate-threads":                 4,
				"write-commit-level-override":      "off",
				"xdr-bin-tombstone-ttl":            86400,
				"xdr-tomb-raider-period":           120,
				"xdr-tomb-raider-threads":          1,
			},
		},
	},
	Conf{"metadata": Conf{"asd_build": "6.4.0.0", "node_id": "BB9030011AC4202"}},
	Conf{
		"namespaces": []Conf{
			{
				"name":                        "bar",
				"allow-ttl-without-nsup":      false,
				"background-query-max-rps":    10000,
				"conflict-resolution-policy":  "generation",
				"conflict-resolve-writes":     false,
				"default-ttl":                 0,
				"disable-cold-start-eviction": false,
				"disable-write-dup-res":       false,
				"disallow-expunge":            false,
				"disallow-null-setname":       false,
				"enable-benchmarks-batch-sub": false,
				"enable-benchmarks-ops-sub":   false,
				"enable-benchmarks-read":      false,
				"enable-benchmarks-udf":       false,
				"enable-benchmarks-udf-sub":   false,
				"enable-benchmarks-write":     false,
				"enable-hist-proxy":           false,
				"evict-hist-buckets":          10000,
				"evict-tenths-pct":            5,
				"geo2dsphere-within": Conf{"earth-radius-meters": 6371000,
					"level-mod": 1,
					"max-cells": 12,
					"max-level": 20,
					"min-level": 1,
					"strict":    true,
				},
				"high-water-disk-pct":       0,
				"high-water-memory-pct":     0,
				"ignore-migrate-fill-delay": false,
				"index-stage-size":          1073741824,
				"index-type":                Conf{"type": "shmem"},
				"inline-short-queries":      false,
				"max-record-size":           0,
				"memory-size":               1073741824,
				"migrate-order":             5,
				"migrate-retransmit-ms":     5000,
				"migrate-sleep":             1,
				"nsup-hist-period":          3600,
				"nsup-period":               0,
				"nsup-threads":              1,
				"partition-tree-sprigs":     256,
				"prefer-uniform-balance":    true,
				"rack-id":                   2,
				"reject-non-xdr-writes":     false,
				"reject-xdr-writes":         false,
				"replication-factor":        1,
				"sets": []Conf{
					{
						"name":              "testset",
						"disable-eviction":  false,
						"enable-index":      false,
						"stop-writes-count": 0,
						"stop-writes-size":  0,
					},
				},
				"sindex-stage-size":          1073741824,
				"sindex-type":                Conf{"type": "shmem"},
				"single-query-threads":       4,
				"stop-writes-pct":            90,
				"stop-writes-sys-memory-pct": 90,
				"storage-engine": Conf{
					"type":                      "device",
					"cache-replica-writes":      false,
					"cold-start-empty":          false,
					"commit-min-size":           0,
					"commit-to-device":          false,
					"compression":               "none",
					"compression-acceleration":  0,
					"compression-level":         0,
					"data-in-memory":            false,
					"defrag-lwm-pct":            50,
					"defrag-queue-min":          0,
					"defrag-sleep":              1000,
					"defrag-startup-minimum":    0,
					"direct-files":              false,
					"disable-odsync":            false,
					"enable-benchmarks-storage": false,
					"files": []string{
						"/opt/aerospike/data/bar.dat /opt/aerospike/data/bar-shadow.dat",
						"/opt/aerospike/data/foo.dat /opt/aerospike/data/foo-shadow.dat",
					},
					"filesize":                   1073741824,
					"flush-max-ms":               1000,
					"max-used-pct":               70,
					"max-write-cache":            67108864,
					"min-avail-pct":              5,
					"post-write-queue":           256,
					"read-page-cache":            false,
					"serialize-tomb-raider":      false,
					"sindex-startup-device-scan": false,
					"tomb-raider-sleep":          1000,
					"write-block-size":           1048576,
				},
				"strong-consistency":               true,
				"strong-consistency-allow-expunge": false,
				"tomb-raider-eligible-age":         86400,
				"tomb-raider-period":               86400,
				"transaction-pending-limit":        20,
				"truncate-threads":                 4,
				"xdr-bin-tombstone-ttl":            86400,
				"xdr-tomb-raider-period":           120,
				"xdr-tomb-raider-threads":          1,
			},
			{
				"name":                        "test",
				"allow-ttl-without-nsup":      false,
				"background-query-max-rps":    10000,
				"conflict-resolution-policy":  "generation",
				"conflict-resolve-writes":     false,
				"default-ttl":                 0,
				"disable-cold-start-eviction": false,
				"disable-write-dup-res":       false,
				"disallow-expunge":            false,
				"disallow-null-setname":       false,
				"enable-benchmarks-batch-sub": false,
				"enable-benchmarks-ops-sub":   false,
				"enable-benchmarks-read":      false,
				"enable-benchmarks-udf":       false,
				"enable-benchmarks-udf-sub":   false,
				"enable-benchmarks-write":     false,
				"enable-hist-proxy":           false,
				"evict-hist-buckets":          10000,
				"evict-tenths-pct":            5,
				"geo2dsphere-within": Conf{"earth-radius-meters": 6371000,
					"level-mod": 1,
					"max-cells": 15,
					"max-level": 20,
					"min-level": 1,
					"strict":    true,
				},
				"high-water-disk-pct":             0,
				"high-water-memory-pct":           0,
				"ignore-migrate-fill-delay":       false,
				"index-stage-size":                1073741824,
				"index-type":                      Conf{"type": "shmem"},
				"inline-short-queries":            false,
				"max-record-size":                 0,
				"memory-size":                     536870912,
				"migrate-order":                   5,
				"migrate-retransmit-ms":           5000,
				"migrate-sleep":                   1,
				"nsup-hist-period":                3600,
				"nsup-period":                     0,
				"nsup-threads":                    1,
				"partition-tree-sprigs":           256,
				"prefer-uniform-balance":          true,
				"rack-id":                         1,
				"read-consistency-level-override": "off",
				"reject-non-xdr-writes":           false,
				"reject-xdr-writes":               false,
				"replication-factor":              1,
				"sets": []Conf{
					{
						"name":              "testset",
						"disable-eviction":  false,
						"enable-index":      false,
						"stop-writes-count": 0,
						"stop-writes-size":  0,
					},
				},
				"sindex-stage-size":          1073741824,
				"sindex-type":                Conf{"type": "shmem"},
				"single-query-threads":       4,
				"stop-writes-pct":            90,
				"stop-writes-sys-memory-pct": 90,
				"storage-engine": Conf{
					"type": "memory",
				},
				"strong-consistency":               false,
				"strong-consistency-allow-expunge": false,
				"tomb-raider-eligible-age":         86400,
				"tomb-raider-period":               86400,
				"transaction-pending-limit":        20,
				"truncate-threads":                 4,
				"write-commit-level-override":      "off",
				"xdr-bin-tombstone-ttl":            86400,
				"xdr-tomb-raider-period":           120,
				"xdr-tomb-raider-threads":          1,
			},
		},
	},
}

var networkTC = GenerateTC{
	"network",
	false,
	Conf{
		"network": Conf{
			"fabric.channel-bulk-fds":           2,
			"fabric.channel-bulk-recv-threads":  4,
			"fabric.channel-ctrl-fds":           1,
			"fabric.channel-ctrl-recv-threads":  4,
			"fabric.channel-meta-fds":           1,
			"fabric.channel-meta-recv-threads":  4,
			"fabric.channel-rw-fds":             8,
			"fabric.channel-rw-recv-pools":      1,
			"fabric.channel-rw-recv-threads":    16,
			"fabric.keepalive-enabled":          true,
			"fabric.keepalive-intvl":            1,
			"fabric.keepalive-probes":           10,
			"fabric.keepalive-time":             1,
			"fabric.latency-max-ms":             5,
			"fabric.port":                       3001,
			"fabric.recv-rearm-threshold":       1024,
			"fabric.send-threads":               8,
			"fabric.tls-name":                   "null",
			"fabric.tls-port":                   0,
			"heartbeat.connect-timeout-ms":      500,
			"heartbeat.interval":                150,
			"heartbeat.mode":                    "multicast",
			"heartbeat.mtu":                     65535,
			"heartbeat.multicast-group":         "239.1.99.222,239.1.99.223",
			"heartbeat.multicast-ttl":           0,
			"heartbeat.port":                    9918,
			"heartbeat.protocol":                "v3",
			"heartbeat.timeout":                 10,
			"info.port":                         3003,
			"service.access-address":            "1.1.1.1,2.2.2.2",
			"service.access-port":               0,
			"service.address":                   "any",
			"service.alternate-access-port":     0,
			"service.disable-localhost":         false,
			"service.port":                      3000,
			"service.tls-access-port":           0,
			"service.tls-alternate-access-port": 0,
			"service.tls-authenticate-client":   false,
			"service.tls-name":                  "aerospike-a-2.test-runner",
			"service.tls-port":                  4333,
			"tls[0].ca-file":                    "null",
			"tls[0].ca-path":                    "null",
			"tls[0].cert-blacklist":             "null",
			"tls[0].cert-file":                  "/data/certs/file0.pem",
			"tls[0].cipher-suite":               "null",
			"tls[0].key-file":                   "/data/certs/key0.pem",
			"tls[0].key-file-password":          "null",
			"tls[0].name":                       "aerospike-a-0",
			"tls[0].protocols":                  "TLSv1.2",
			"tls[1].ca-file":                    "null",
			"tls[1].ca-path":                    "null",
			"tls[1].cert-blacklist":             "null",
			"tls[1].cert-file":                  "/data/certs/file1.pem",
			"tls[1].cipher-suite":               "null",
			"tls[1].key-file":                   "/data/certs/key1.pem",
			"tls[1].key-file-password":          "null",
			"tls[1].name":                       "aerospike-a-1",
			"tls[1].protocols":                  "TLSv1.2",
		},
	},
	Conf{"metadata": Conf{"asd_build": "6.4.0.0", "node_id": "BB9030011AC4202"}},
	Conf{
		"network": Conf{
			"fabric": Conf{
				"channel-bulk-fds":          2,
				"channel-bulk-recv-threads": 4,
				"channel-ctrl-fds":          1,
				"channel-ctrl-recv-threads": 4,
				"channel-meta-fds":          1,
				"channel-meta-recv-threads": 4,
				"channel-rw-fds":            8,
				"channel-rw-recv-pools":     1,
				"channel-rw-recv-threads":   16,
				"keepalive-enabled":         true,
				"keepalive-intvl":           1,
				"keepalive-probes":          10,
				"keepalive-time":            1,
				"latency-max-ms":            5,
				"port":                      3001,
				"recv-rearm-threshold":      1024,
				"send-threads":              8,
				"tls-port":                  0,
			},
			"heartbeat": Conf{
				"connect-timeout-ms": 500,
				"interval":           150,
				"mode":               "multicast",
				"mtu":                65535,
				"multicast-groups":   []string{"239.1.99.222", "239.1.99.223"},
				"multicast-ttl":      0,
				"port":               9918,
				"protocol":           "v3",
				"timeout":            10,
			},
			"info": Conf{
				"port": 3003,
			},
			"service": Conf{
				"access-addresses":          []string{"1.1.1.1", "2.2.2.2"},
				"access-port":               0,
				"addresses":                 []string{"any"},
				"alternate-access-port":     0,
				"disable-localhost":         false,
				"port":                      3000,
				"tls-access-port":           0,
				"tls-alternate-access-port": 0,
				"tls-name":                  "aerospike-a-2.test-runner",
				"tls-port":                  4333,
				"tls-authenticate-client":   false,
			},
			"tls": []Conf{
				{
					"cert-file": "/data/certs/file0.pem",
					"key-file":  "/data/certs/key0.pem",
					"name":      "aerospike-a-0",
					"protocols": "TLSv1.2",
				},
				{
					"cert-file": "/data/certs/file1.pem",
					"key-file":  "/data/certs/key1.pem",
					"name":      "aerospike-a-1",
					"protocols": "TLSv1.2",
				},
			},
		},
	},
}

var securityEnabled57TC = GenerateTC{
	"security post 5.7",
	false,
	Conf{
		"security": Conf{
			"enable-quotas":             true,
			"enable-security":           true,
			"log.report-authentication": false,
			"log.report-sys-admin":      false,
			"log.report-user-admin":     false,
			"log.report-violation":      false,
			"privilege-refresh-period":  300,
			"session-ttl":               86400,
			"tps-weight":                2,
		},
	},
	Conf{"metadata": Conf{"asd_build": "6.4.0.0", "node_id": "BB9030011AC4202"}},
	Conf{
		"security": Conf{
			"enable-quotas": true,
			"log": Conf{
				"report-authentication": false,
				"report-sys-admin":      false,
				"report-user-admin":     false,
				"report-violation":      false,
			},
			"privilege-refresh-period": 300,
			"session-ttl":              86400,
			"tps-weight":               2,
		},
	},
}

var securityDisabled57TC = GenerateTC{
	"security post 5.7",
	false,
	Conf{
		"security": Conf{
			"enable-quotas":             true,
			"enable-security":           false,
			"log.report-authentication": false,
			"log.report-sys-admin":      false,
			"log.report-user-admin":     false,
			"log.report-violation":      false,
			"privilege-refresh-period":  300,
			"session-ttl":               86400,
			"tps-weight":                2,
		},
	},
	Conf{"metadata": Conf{"asd_build": "6.4.0.0", "node_id": "BB9030011AC4202"}},
	Conf{},
}

var securityEnabled56TC = GenerateTC{
	"security pre 5.7",
	false,
	Conf{
		"security": Conf{
			"enable-quotas":             true,
			"enable-security":           true,
			"log.report-authentication": false,
			"log.report-sys-admin":      false,
			"log.report-user-admin":     false,
			"log.report-violation":      false,
			"privilege-refresh-period":  300,
			"tps-weight":                2,
		},
	},
	Conf{"metadata": Conf{"asd_build": "5.6.0.0", "node_id": "BB9030011AC4202"}},
	Conf{
		"security": Conf{
			"enable-quotas":   true,
			"enable-security": true,
			"log": Conf{
				"report-authentication": false,
				"report-sys-admin":      false,
				"report-user-admin":     false,
				"report-violation":      false,
			},
			"privilege-refresh-period": 300,
			"tps-weight":               2,
		},
	},
}

var securityDisabled56TC = GenerateTC{
	"security pre 5.7",
	false,
	Conf{
		"security": Conf{
			"enable-quotas":             true,
			"enable-security":           false,
			"log.report-authentication": false,
			"log.report-sys-admin":      false,
			"log.report-user-admin":     false,
			"log.report-violation":      false,
			"ldap.session-ttl":          86400,
			"privilege-refresh-period":  300,
			"tps-weight":                2,
		},
	},
	Conf{"metadata": Conf{"asd_build": "5.6.0.0", "node_id": "BB9030011AC4202"}},
	Conf{
		"security": Conf{
			"enable-quotas":   true,
			"enable-security": false,
			"log": Conf{
				"report-authentication": false,
				"report-sys-admin":      false,
				"report-user-admin":     false,
				"report-violation":      false,
			},
			"ldap": Conf{
				"session-ttl": 86400,
			},
			"privilege-refresh-period": 300,
			"tps-weight":               2,
		},
	},
}

var serviceTC = GenerateTC{
	"service",
	false,
	Conf{
		"service": Conf{
			"advertise-ipv6":              false,
			"auto-pin":                    "none",
			"batch-index-threads":         8,
			"batch-max-buffers-per-queue": 255,
			"batch-max-unused-buffers":    256,
			"cluster-name":                "6.x-cluster-security",
			"debug-allocations":           "none",
			"disable-udf-execution":       false,
			"downgrading":                 false,
			"enable-benchmarks-fabric":    false,
			"enable-health-check":         false,
			"enable-hist-info":            false,
			"enforce-best-practices":      false,
			"feature-key-file[0]":         "/etc/aerospike/features.conf",
			"indent-allocations":          false,
			"info-max-ms":                 10000,
			"info-threads":                16,
			"keep-caps-ssd-health":        false,
			"log-local-time":              false,
			"log-millis":                  false,
			"microsecond-histograms":      false,
			"migrate-fill-delay":          0,
			"migrate-max-num-incoming":    4,
			"migrate-threads":             1,
			"min-cluster-size":            1,
			"node-id":                     "BB9050011AC4202",
			"node-id-interface":           "null",
			"os-group-perms":              false,
			"pidfile":                     "null",
			"proto-fd-idle-ms":            0,
			"proto-fd-max":                15000,
			"query-max-done":              100,
			"query-threads-limit":         128,
			"run-as-daemon":               true,
			"salt-allocations":            false,
			"secrets-address-port":        "null",
			"secrets-tls-context":         "null",
			"service-threads":             8,
			"sindex-builder-threads":      4,
			"sindex-gc-period":            10,
			"stay-quiesced":               false,
			"ticker-interval":             10,
			"transaction-max-ms":          1000,
			"transaction-retry-ms":        1002,
			"vault-ca":                    "null",
			"vault-namespace":             "null",
			"vault-path":                  "null",
			"vault-token-file":            "null",
			"vault-url":                   "null",
			"work-directory":              "/opt/aerospike",
		},
	},
	Conf{"metadata": Conf{"asd_build": "6.4.0.0", "node_id": "BB9030011AC4202"}},
	Conf{
		"service": Conf{
			"advertise-ipv6":              false,
			"auto-pin":                    "none",
			"batch-index-threads":         8,
			"batch-max-buffers-per-queue": 255,
			"batch-max-unused-buffers":    256,
			"cluster-name":                "6.x-cluster-security",
			"debug-allocations":           "none",
			"disable-udf-execution":       false,
			"enable-benchmarks-fabric":    false,
			"enable-health-check":         false,
			"enable-hist-info":            false,
			"enforce-best-practices":      false,
			"feature-key-files":           []string{"/etc/aerospike/features.conf"},
			"indent-allocations":          false,
			"info-max-ms":                 10000,
			"info-threads":                16,
			"keep-caps-ssd-health":        false,
			"log-local-time":              false,
			"log-millis":                  false,
			"microsecond-histograms":      false,
			"migrate-fill-delay":          0,
			"migrate-max-num-incoming":    4,
			"migrate-threads":             1,
			"min-cluster-size":            1,
			"node-id":                     "BB9050011AC4202",
			"os-group-perms":              false,
			"proto-fd-idle-ms":            0,
			"proto-fd-max":                15000,
			"query-max-done":              100,
			"query-threads-limit":         128,
			"run-as-daemon":               true,
			"salt-allocations":            false,
			"service-threads":             8,
			"sindex-builder-threads":      4,
			"sindex-gc-period":            10,
			"stay-quiesced":               false,
			"ticker-interval":             10,
			"transaction-max-ms":          1000,
			"transaction-retry-ms":        1002,
			"work-directory":              "/opt/aerospike",
		},
	},
}

var xdrTC = GenerateTC{
	"xdr post 6",
	false,
	Conf{
		"xdr": Conf{
			"dcs": Conf{
				"DC1": Conf{
					"auth-mode":                  "none",
					"auth-password-file":         "null",
					"auth-user":                  "null",
					"connector":                  false,
					"max-recoveries-interleaved": 0,
					"namespaces": Conf{
						"test": Conf{
							"bin-policy":               "changed-or-specified",
							"compression-level":        1,
							"compression-threshold":    128,
							"delay-ms":                 0,
							"enable-compression":       false,
							"forward":                  false,
							"hot-key-ms":               100,
							"ignore-expunges":          false,
							"ignored-bins":             "",
							"ignored-sets":             "",
							"max-throughput":           100000,
							"remote-namespace":         "null",
							"sc-replication-wait-ms":   100,
							"ship-bin-luts":            false,
							"ship-nsup-deletes":        false,
							"ship-only-specified-sets": false,
							"shipped-bins":             "foo,bar",
							"shipped-sets":             "blah,blee",
							"transaction-queue-limit":  16384,
							"write-policy":             "auto",
						},
					},
					"node-address-port":            "",
					"period-ms":                    100,
					"tls-name":                     "null",
					"use-alternate-access-address": false,
				},
				"DC2": Conf{
					"auth-mode":                  "none",
					"auth-password-file":         "null",
					"auth-user":                  "null",
					"connector":                  false,
					"max-recoveries-interleaved": 0,
					"namespaces": Conf{
						"bar": Conf{
							"bin-policy":               "all",
							"compression-level":        1,
							"compression-threshold":    128,
							"delay-ms":                 0,
							"enable-compression":       false,
							"enabled":                  true,
							"forward":                  false,
							"hot-key-ms":               100,
							"ignore-expunges":          false,
							"ignored-bins":             "tip,wip",
							"ignored-sets":             "zip,zap",
							"max-throughput":           100000,
							"remote-namespace":         "null",
							"sc-replication-wait-ms":   100,
							"ship-bin-luts":            false,
							"ship-nsup-deletes":        false,
							"ship-only-specified-sets": false,
							"shipped-bins":             "",
							"shipped-sets":             "",
							"transaction-queue-limit":  16384,
							"write-policy":             "auto",
						},
					},
					"node-address-port":            "",
					"period-ms":                    100,
					"tls-name":                     "null",
					"use-alternate-access-address": false,
				},
			},
			"src-id":       0,
			"trace-sample": 0,
		},
	},
	Conf{"metadata": Conf{"asd_build": "6.4.0.0", "node_id": "BB9030011AC4202"}},
	Conf{
		"xdr": Conf{
			"dcs": []Conf{
				{
					"name":                       "DC1",
					"auth-mode":                  "none",
					"connector":                  false,
					"max-recoveries-interleaved": 0,
					"namespaces": []Conf{
						{
							"name":                     "test",
							"bin-policy":               "changed-or-specified",
							"compression-level":        1,
							"compression-threshold":    128,
							"delay-ms":                 0,
							"enable-compression":       false,
							"forward":                  false,
							"hot-key-ms":               100,
							"ignore-expunges":          false,
							"ignore-bins":              []string{},
							"ignore-sets":              []string{},
							"max-throughput":           100000,
							"sc-replication-wait-ms":   100,
							"ship-bin-luts":            false,
							"ship-nsup-deletes":        false,
							"ship-only-specified-sets": false,
							"ship-bins":                []string{"foo", "bar"},
							"ship-sets":                []string{"blah", "blee"},
							"transaction-queue-limit":  16384,
							"write-policy":             "auto",
						},
					},
					"node-address-ports":           []string{},
					"period-ms":                    100,
					"use-alternate-access-address": false,
				},
				{
					"name":                       "DC2",
					"auth-mode":                  "none",
					"connector":                  false,
					"max-recoveries-interleaved": 0,
					"namespaces": []Conf{
						{
							"name":                     "bar",
							"bin-policy":               "all",
							"compression-level":        1,
							"compression-threshold":    128,
							"delay-ms":                 0,
							"enable-compression":       false,
							"forward":                  false,
							"hot-key-ms":               100,
							"ignore-expunges":          false,
							"ignore-bins":              []string{"tip", "wip"},
							"ignore-sets":              []string{"zip", "zap"},
							"max-throughput":           100000,
							"sc-replication-wait-ms":   100,
							"ship-bin-luts":            false,
							"ship-nsup-deletes":        false,
							"ship-only-specified-sets": false,
							"ship-bins":                []string{},
							"ship-sets":                []string{},
							"transaction-queue-limit":  16384,
							"write-policy":             "auto",
						},
					},
					"node-address-ports":           []string{},
					"period-ms":                    100,
					"use-alternate-access-address": false,
				},
			},
			"src-id": 0,
		},
	},
}

// Same as above but remove defaults
var loggingDefaultsTC = GenerateTC{
	"logging with remove default",
	true,
	Conf{
		"logging": Conf{
			"/var/log/aerospike/aerospike.log": Conf{
				"aggr":         "INFO",
				"alloc":        "INFO",
				"appeal":       "INFO",
				"arenax":       "INFO",
				"as":           "INFO",
				"audit":        "INFO",
				"batch":        "INFO",
				"batch-sub":    "INFO",
				"bin":          "INFO",
				"clustering":   "INFO",
				"config":       "INFO",
				"drv_pmem":     "INFO",
				"drv_ssd":      "INFO",
				"exchange":     "INFO",
				"exp":          "INFO",
				"fabric":       "INFO",
				"flat":         "INFO",
				"geo":          "INFO",
				"hardware":     "INFO",
				"hb":           "INFO",
				"health":       "INFO",
				"hlc":          "INFO",
				"index":        "INFO",
				"info":         "INFO",
				"info-port":    "INFO",
				"key-busy":     "INFO",
				"migrate":      "INFO",
				"misc":         "INFO",
				"msg":          "INFO",
				"namespace":    "INFO",
				"nsup":         "INFO",
				"os":           "INFO",
				"particle":     "INFO",
				"partition":    "INFO",
				"proto":        "INFO",
				"proxy":        "INFO",
				"proxy-divert": "INFO",
				"query":        "INFO",
				"record":       "INFO",
				"roster":       "INFO",
				"rw":           "INFO",
				"rw-client":    "INFO",
				"secrets":      "INFO",
				"security":     "INFO",
				"service":      "INFO",
				"service-list": "INFO",
				"sindex":       "INFO",
				"skew":         "INFO",
				"smd":          "INFO",
				"socket":       "INFO",
				"storage":      "INFO",
				"tls":          "INFO",
				"truncate":     "INFO",
				"tsvc":         "INFO",
				"udf":          "INFO",
				"vault":        "INFO",
				"vmapx":        "INFO",
				"xdr":          "INFO",
				"xdr-client":   "INFO",
				"xmem":         "INFO",
			},
			"stderr": Conf{
				"aggr":         "CRITICAL",
				"alloc":        "WARNING",
				"appeal":       "DEBUG",
				"arenax":       "DETAIL",
				"as":           "INFO",
				"audit":        "INFO",
				"batch":        "INFO",
				"batch-sub":    "INFO",
				"bin":          "INFO",
				"clustering":   "INFO",
				"config":       "INFO",
				"drv_pmem":     "INFO",
				"drv_ssd":      "INFO",
				"exchange":     "INFO",
				"exp":          "INFO",
				"fabric":       "INFO",
				"flat":         "INFO",
				"geo":          "INFO",
				"hardware":     "INFO",
				"hb":           "INFO",
				"health":       "INFO",
				"hlc":          "INFO",
				"index":        "INFO",
				"info":         "INFO",
				"info-port":    "INFO",
				"key-busy":     "INFO",
				"migrate":      "INFO",
				"misc":         "INFO",
				"msg":          "INFO",
				"namespace":    "INFO",
				"nsup":         "INFO",
				"os":           "INFO",
				"particle":     "INFO",
				"partition":    "INFO",
				"proto":        "INFO",
				"proxy":        "INFO",
				"proxy-divert": "INFO",
				"query":        "INFO",
				"record":       "INFO",
				"roster":       "INFO",
				"rw":           "INFO",
				"rw-client":    "INFO",
				"secrets":      "INFO",
				"security":     "INFO",
				"service":      "INFO",
				"service-list": "INFO",
				"sindex":       "INFO",
				"skew":         "INFO",
				"smd":          "INFO",
				"socket":       "INFO",
				"storage":      "INFO",
				"tls":          "INFO",
				"truncate":     "INFO",
				"tsvc":         "INFO",
				"udf":          "INFO",
				"vault":        "INFO",
				"vmapx":        "INFO",
				"xdr":          "INFO",
				"xdr-client":   "INFO",
				"xmem":         "INFO",
			},
			"/dev/log": Conf{
				"some-other":   "keep this",
				"aggr":         "CRITICAL",
				"alloc":        "CRITICAL",
				"appeal":       "CRITICAL",
				"arenax":       "CRITICAL",
				"as":           "CRITICAL",
				"audit":        "CRITICAL",
				"batch":        "CRITICAL",
				"batch-sub":    "CRITICAL",
				"bin":          "CRITICAL",
				"clustering":   "CRITICAL",
				"config":       "CRITICAL",
				"drv_pmem":     "CRITICAL",
				"drv_ssd":      "CRITICAL",
				"exchange":     "CRITICAL",
				"exp":          "CRITICAL",
				"fabric":       "CRITICAL",
				"flat":         "CRITICAL",
				"geo":          "CRITICAL",
				"hardware":     "CRITICAL",
				"hb":           "CRITICAL",
				"health":       "CRITICAL",
				"hlc":          "CRITICAL",
				"index":        "CRITICAL",
				"info":         "CRITICAL",
				"info-port":    "CRITICAL",
				"key-busy":     "CRITICAL",
				"migrate":      "CRITICAL",
				"misc":         "CRITICAL",
				"msg":          "CRITICAL",
				"namespace":    "CRITICAL",
				"nsup":         "CRITICAL",
				"os":           "CRITICAL",
				"particle":     "CRITICAL",
				"partition":    "CRITICAL",
				"proto":        "CRITICAL",
				"proxy":        "CRITICAL",
				"proxy-divert": "CRITICAL",
				"query":        "CRITICAL",
				"record":       "CRITICAL",
				"roster":       "CRITICAL",
				"rw":           "CRITICAL",
				"rw-client":    "CRITICAL",
				"secrets":      "CRITICAL",
				"security":     "CRITICAL",
				"service":      "CRITICAL",
				"service-list": "CRITICAL",
				"sindex":       "CRITICAL",
				"skew":         "CRITICAL",
				"smd":          "CRITICAL",
				"socket":       "CRITICAL",
				"storage":      "CRITICAL",
				"tls":          "CRITICAL",
				"truncate":     "CRITICAL",
				"tsvc":         "CRITICAL",
				"udf":          "CRITICAL",
				"vault":        "CRITICAL",
				"vmapx":        "CRITICAL",
				"xdr":          "CRITICAL",
				"xdr-client":   "CRITICAL",
				"xmem":         "CRITICAL",
			},
		},
	},
	Conf{"metadata": Conf{"asd_build": "6.4.0.0", "node_id": "BB9030011AC4202"}},
	Conf{
		"logging": []Conf{
			{
				"name": "/var/log/aerospike/aerospike.log",
				"any":  "INFO",
			},
			{
				"name":   "console",
				"aggr":   "CRITICAL",
				"alloc":  "WARNING",
				"appeal": "DEBUG",
				"arenax": "DETAIL",
				"any":    "INFO",
			},
			{
				"name": "syslog",
				"path": "/dev/log",
				"any":  "CRITICAL",
			},
		},
	},
}

var namespacesDefaultsTC = GenerateTC{
	"namespaces with remove defaults",
	true,
	Conf{
		"racks": []Conf{
			{
				"ns":     "test",
				"rack_1": "BB9030011AC4202",
				"rack_0": "BB9030011AC4203",
			},
			{
				"ns":     "bar",
				"rack_2": "BB9030011AC4202",
				"rack_0": "BB9030011AC4203",
			},
		},
		"namespaces": Conf{
			"bar": Conf{
				"allow-ttl-without-nsup":                 false,
				"background-query-max-rps":               10000,
				"conflict-resolution-policy":             "generation",
				"conflict-resolve-writes":                false,
				"default-ttl":                            0,
				"disable-cold-start-eviction":            false,
				"disable-write-dup-res":                  false,
				"disallow-expunge":                       false,
				"disallow-null-setname":                  false,
				"enable-benchmarks-batch-sub":            false,
				"enable-benchmarks-ops-sub":              false,
				"enable-benchmarks-read":                 false,
				"enable-benchmarks-udf":                  false,
				"enable-benchmarks-udf-sub":              false,
				"enable-benchmarks-write":                false,
				"enable-hist-proxy":                      false,
				"evict-hist-buckets":                     10000,
				"evict-tenths-pct":                       5,
				"force-long-queries":                     false,
				"geo2dsphere-within.earth-radius-meters": 6371000,
				"geo2dsphere-within.level-mod":           1,
				"geo2dsphere-within.max-cells":           12,
				"geo2dsphere-within.max-level":           20,
				"geo2dsphere-within.min-level":           1,
				"geo2dsphere-within.strict":              true,
				"high-water-disk-pct":                    0,
				"high-water-memory-pct":                  0,
				"ignore-migrate-fill-delay":              false,
				"index-stage-size":                       1073741824,
				"index-type":                             "shmem",
				"inline-short-queries":                   false,
				"max-record-size":                        0,
				"memory-size":                            1073741824,
				"migrate-order":                          5,
				"migrate-retransmit-ms":                  5000,
				"migrate-sleep":                          1,
				"nsup-hist-period":                       3600,
				"nsup-period":                            0,
				"nsup-threads":                           1,
				"partition-tree-sprigs":                  256,
				"prefer-uniform-balance":                 true,
				"rack-id":                                0,
				"read-consistency-level-override":        "off",
				"reject-non-xdr-writes":                  false,
				"reject-xdr-writes":                      false,
				"replication-factor":                     1,
				"sets": Conf{
					"testset": Conf{
						"disable-eviction":  false,
						"enable-index":      false,
						"stop-writes-count": 0,
						"stop-writes-size":  0,
					},
				},
				"sindex-stage-size":                         1073741824,
				"sindex-type":                               "shmem",
				"single-query-threads":                      4,
				"stop-writes-pct":                           90,
				"stop-writes-sys-memory-pct":                90,
				"storage-engine":                            "device",
				"storage-engine.cache-replica-writes":       false,
				"storage-engine.cold-start-empty":           false,
				"storage-engine.commit-min-size":            0,
				"storage-engine.commit-to-device":           false,
				"storage-engine.compression":                "none",
				"storage-engine.compression-acceleration":   0,
				"storage-engine.compression-level":          0,
				"storage-engine.data-in-memory":             false,
				"storage-engine.defrag-lwm-pct":             50,
				"storage-engine.defrag-queue-min":           0,
				"storage-engine.defrag-sleep":               1000,
				"storage-engine.defrag-startup-minimum":     0,
				"storage-engine.direct-files":               false,
				"storage-engine.disable-odsync":             false,
				"storage-engine.enable-benchmarks-storage":  false,
				"storage-engine.encryption-key-file":        "null",
				"storage-engine.encryption-old-key-file":    "null",
				"storage-engine.file[0]":                    "/opt/aerospike/data/bar.dat",
				"storage-engine.file[0].shadow":             "/opt/aerospike/data/bar-shadow.dat",
				"storage-engine.file[1]":                    "/opt/aerospike/data/foo.dat",
				"storage-engine.file[1].shadow":             "/opt/aerospike/data/foo-shadow.dat",
				"storage-engine.filesize":                   1073741824,
				"storage-engine.flush-max-ms":               1000,
				"storage-engine.max-used-pct":               70,
				"storage-engine.max-write-cache":            67108864,
				"storage-engine.min-avail-pct":              5,
				"storage-engine.post-write-queue":           256,
				"storage-engine.read-page-cache":            false,
				"storage-engine.serialize-tomb-raider":      false,
				"storage-engine.sindex-startup-device-scan": false,
				"storage-engine.tomb-raider-sleep":          1000,
				"storage-engine.write-block-size":           1048576,
				"strong-consistency":                        true,
				"strong-consistency-allow-expunge":          false,
				"tomb-raider-eligible-age":                  86400,
				"tomb-raider-period":                        86400,
				"transaction-pending-limit":                 20,
				"truncate-threads":                          4,
				"write-commit-level-override":               "off",
				"xdr-bin-tombstone-ttl":                     86400,
				"xdr-tomb-raider-period":                    120,
				"xdr-tomb-raider-threads":                   1,
			},
			"test": Conf{
				"allow-ttl-without-nsup":                 false,
				"background-query-max-rps":               10000,
				"conflict-resolution-policy":             "generation",
				"conflict-resolve-writes":                false,
				"default-ttl":                            0,
				"disable-cold-start-eviction":            false,
				"disable-write-dup-res":                  false,
				"disallow-expunge":                       false,
				"disallow-null-setname":                  false,
				"enable-benchmarks-batch-sub":            false,
				"enable-benchmarks-ops-sub":              false,
				"enable-benchmarks-read":                 false,
				"enable-benchmarks-udf":                  false,
				"enable-benchmarks-udf-sub":              false,
				"enable-benchmarks-write":                false,
				"enable-hist-proxy":                      false,
				"evict-hist-buckets":                     10000,
				"evict-tenths-pct":                       5,
				"force-long-queries":                     false,
				"geo2dsphere-within.earth-radius-meters": 6371000,
				"geo2dsphere-within.level-mod":           1,
				"geo2dsphere-within.max-cells":           15,
				"geo2dsphere-within.max-level":           20,
				"geo2dsphere-within.min-level":           1,
				"geo2dsphere-within.strict":              true,
				"high-water-disk-pct":                    0,
				"high-water-memory-pct":                  0,
				"ignore-migrate-fill-delay":              false,
				"index-stage-size":                       1073741824,
				"index-type":                             "shmem",
				"inline-short-queries":                   false,
				"max-record-size":                        0,
				"memory-size":                            536870912,
				"migrate-order":                          5,
				"migrate-retransmit-ms":                  5000,
				"migrate-sleep":                          1,
				"nsup-hist-period":                       3600,
				"nsup-period":                            0,
				"nsup-threads":                           1,
				"partition-tree-sprigs":                  256,
				"prefer-uniform-balance":                 true,
				"rack-id":                                0,
				"read-consistency-level-override":        "off",
				"reject-non-xdr-writes":                  false,
				"reject-xdr-writes":                      false,
				"replication-factor":                     1,
				"sets": Conf{
					"testset": Conf{
						"disable-eviction":  false,
						"enable-index":      false,
						"stop-writes-count": 0,
						"stop-writes-size":  0,
					},
				},
				"sindex-stage-size":                1073741824,
				"sindex-type":                      "shmem",
				"single-query-threads":             4,
				"stop-writes-pct":                  90,
				"stop-writes-sys-memory-pct":       90,
				"storage-engine":                   "memory",
				"strong-consistency":               false,
				"strong-consistency-allow-expunge": false,
				"tomb-raider-eligible-age":         86400,
				"tomb-raider-period":               86400,
				"transaction-pending-limit":        20,
				"truncate-threads":                 4,
				"write-commit-level-override":      "off",
				"xdr-bin-tombstone-ttl":            86400,
				"xdr-tomb-raider-period":           120,
				"xdr-tomb-raider-threads":          1,
			},
		},
	},
	Conf{"metadata": Conf{"asd_build": "6.4.0.0", "node_id": "BB9030011AC4202"}},
	Conf{
		"namespaces": []Conf{
			{
				"name":               "bar",
				"memory-size":        1073741824,
				"rack-id":            2,
				"replication-factor": 1,
				"sets": []Conf{
					{
						"name": "testset",
					},
				},
				"index-type": Conf{
					"type": "shmem",
				},
				"sindex-type": Conf{
					"type": "shmem",
				},
				"storage-engine": Conf{
					"type": "device",
					"files": []string{
						"/opt/aerospike/data/bar.dat /opt/aerospike/data/bar-shadow.dat",
						"/opt/aerospike/data/foo.dat /opt/aerospike/data/foo-shadow.dat",
					},
					"filesize": 1073741824,
				},
				"strong-consistency": true,
			},
			{
				"name":        "test",
				"memory-size": 536870912,
				"geo2dsphere-within": Conf{
					"max-cells": 15,
				},
				"rack-id":            1,
				"replication-factor": 1,
				"sets": []Conf{
					{
						"name": "testset",
					},
				},
				"index-type": Conf{
					"type": "shmem",
				},
				"sindex-type": Conf{
					"type": "shmem",
				},
				"storage-engine": Conf{
					"type": "memory",
				},
			},
		},
	},
}

var networkDefaultsTC = GenerateTC{
	"network with remove defaults",
	true,
	Conf{
		"network": Conf{
			"fabric.channel-bulk-fds":           2,
			"fabric.channel-bulk-recv-threads":  4,
			"fabric.channel-ctrl-fds":           1,
			"fabric.channel-ctrl-recv-threads":  4,
			"fabric.channel-meta-fds":           1,
			"fabric.channel-meta-recv-threads":  4,
			"fabric.channel-rw-fds":             8,
			"fabric.channel-rw-recv-pools":      1,
			"fabric.channel-rw-recv-threads":    16,
			"fabric.keepalive-enabled":          true,
			"fabric.keepalive-intvl":            1,
			"fabric.keepalive-probes":           10,
			"fabric.keepalive-time":             1,
			"fabric.latency-max-ms":             5,
			"fabric.port":                       3001,
			"fabric.recv-rearm-threshold":       1024,
			"fabric.send-threads":               8,
			"fabric.tls-name":                   "null",
			"fabric.tls-port":                   0,
			"heartbeat.connect-timeout-ms":      500,
			"heartbeat.interval":                151,
			"heartbeat.mode":                    "multicast",
			"heartbeat.mtu":                     65535,
			"heartbeat.multicast-group":         "239.1.99.222,239.1.99.223",
			"heartbeat.multicast-ttl":           0,
			"heartbeat.port":                    9918,
			"heartbeat.protocol":                "v3",
			"heartbeat.timeout":                 10,
			"info.port":                         3003,
			"service.access-address":            "1.1.1.1,2.2.2.2",
			"service.access-port":               0,
			"service.address":                   "any",
			"service.alternate-access-port":     0,
			"service.disable-localhost":         false,
			"service.port":                      3000,
			"service.tls-access-port":           0,
			"service.tls-alternate-access-port": 0,
			"service.tls-name":                  "null",
			"service.tls-port":                  0,
			"service.tls-authenticate-client":   "any",
		},
	},
	Conf{"metadata": Conf{"asd_build": "6.4.0.0", "node_id": "BB9030011AC4202"}},
	Conf{
		"network": Conf{
			"fabric": Conf{
				"port": 3001,
			},
			"heartbeat": Conf{
				"interval":         151,
				"mode":             "multicast",
				"multicast-groups": []string{"239.1.99.222", "239.1.99.223"},
				"port":             9918,
				"mtu":              65535,
			},
			"info": Conf{
				"port": 3003,
			},
			"service": Conf{
				"access-addresses": []string{"1.1.1.1", "2.2.2.2"},
				"addresses":        []string{"any"},
				"port":             3000,
			},
		},
	},
}

var security57DefaultsTC = GenerateTC{
	"security post 5.7 with remove defaults",
	true,
	Conf{
		"security": Conf{
			"enable-quotas":             true,
			"enable-security":           true,
			"log.report-authentication": false,
			"log.report-sys-admin":      false,
			"log.report-user-admin":     false,
			"log.report-violation":      false,
			"privilege-refresh-period":  300,
			"session-ttl":               86400,
			"tps-weight":                2,
		},
	},
	Conf{"metadata": Conf{"asd_build": "6.4.0.0", "node_id": "BB9030011AC4202"}},
	Conf{
		"security": Conf{
			"enable-quotas": true,
		},
	},
}

var security57AllDefaultsTC = GenerateTC{
	"security post 5.7 with remove defaults",
	true,
	Conf{
		"security": Conf{
			"enable-quotas":             false,
			"enable-security":           true,
			"log.report-authentication": false,
			"log.report-sys-admin":      false,
			"log.report-user-admin":     false,
			"log.report-violation":      false,
			"privilege-refresh-period":  300,
			"session-ttl":               86400,
			"tps-weight":                2,
		},
	},
	Conf{"metadata": Conf{"asd_build": "6.4.0.0", "node_id": "BB9030011AC4202"}},
	Conf{
		"security": Conf{},
	},
}

var serviceDefaultsTC = GenerateTC{
	"service with remove defaults",
	true,
	Conf{
		"service": Conf{
			"advertise-ipv6":              false,
			"auto-pin":                    "none",
			"batch-index-threads":         8,
			"batch-max-buffers-per-queue": 255,
			"batch-max-unused-buffers":    256,
			"cluster-name":                "6.x-cluster-security",
			"debug-allocations":           "none",
			"disable-udf-execution":       false,
			"downgrading":                 false,
			"enable-benchmarks-fabric":    false,
			"enable-health-check":         false,
			"enable-hist-info":            false,
			"enforce-best-practices":      false,
			"feature-key-file[0]":         "/etc/aerospike/features-non-default.conf",
			"indent-allocations":          false,
			"info-max-ms":                 10000,
			"info-threads":                16,
			"keep-caps-ssd-health":        false,
			"log-local-time":              false,
			"log-millis":                  false,
			"microsecond-histograms":      false,
			"migrate-fill-delay":          0,
			"migrate-max-num-incoming":    4,
			"migrate-threads":             1,
			"min-cluster-size":            1,
			"node-id":                     "BB9050011AC4202",
			"node-id-interface":           "null",
			"os-group-perms":              false,
			"pidfile":                     "null",
			"proto-fd-idle-ms":            0,
			"proto-fd-max":                15001,
			"query-max-done":              100,
			"query-threads-limit":         128,
			"run-as-daemon":               true,
			"salt-allocations":            false,
			"secrets-address-port":        "null",
			"secrets-tls-context":         "null",
			"service-threads":             8,
			"sindex-builder-threads":      4,
			"sindex-gc-period":            10,
			"stay-quiesced":               false,
			"ticker-interval":             10,
			"transaction-max-ms":          1000,
			"transaction-retry-ms":        1002,
			"vault-ca":                    "null",
			"vault-namespace":             "null",
			"vault-path":                  "null",
			"vault-token-file":            "null",
			"vault-url":                   "null",
			"work-directory":              "/opt/aerospike",
		},
	},
	Conf{"metadata": Conf{"asd_build": "6.4.0.0", "node_id": "BB9030011AC4202"}},
	Conf{
		"service": Conf{
			"cluster-name": "6.x-cluster-security",
			"proto-fd-max": 15001,
			"feature-key-files": []string{
				"/etc/aerospike/features-non-default.conf",
			},
			"node-id":             "BB9050011AC4202",
			"service-threads":     8,
			"batch-index-threads": 8,
		},
	},
}

var xdrDefaultsTC = GenerateTC{
	"xdr post 6 with remove defaults",
	true,
	Conf{
		"xdr": Conf{
			"dcs": Conf{
				"DC1": Conf{
					"auth-mode":                  "none",
					"auth-password-file":         "null",
					"auth-user":                  "null",
					"connector":                  false,
					"max-recoveries-interleaved": 0,
					"namespaces": Conf{
						"test": Conf{
							"bin-policy":               "changed-or-specified",
							"compression-level":        1,
							"compression-threshold":    128,
							"delay-ms":                 0,
							"enable-compression":       false,
							"enabled":                  true,
							"forward":                  false,
							"hot-key-ms":               100,
							"ignore-expunges":          false,
							"ignored-bins":             "",
							"ignored-sets":             "",
							"max-throughput":           100000,
							"remote-namespace":         "null",
							"sc-replication-wait-ms":   100,
							"ship-bin-luts":            false,
							"ship-nsup-deletes":        false,
							"ship-only-specified-sets": false,
							"shipped-bins":             "foo,bar",
							"shipped-sets":             "blah,blee",
							"transaction-queue-limit":  16384,
							"write-policy":             "auto",
						},
					},
					"node-address-port":            "",
					"period-ms":                    100,
					"tls-name":                     "null",
					"use-alternate-access-address": false,
				},
				"DC2": Conf{
					"auth-mode":                  "none",
					"auth-password-file":         "null",
					"auth-user":                  "null",
					"connector":                  false,
					"max-recoveries-interleaved": 0,
					"namespaces": Conf{
						"bar": Conf{
							"bin-policy":               "all",
							"compression-level":        1,
							"compression-threshold":    128,
							"delay-ms":                 0,
							"enable-compression":       false,
							"enabled":                  true,
							"forward":                  false,
							"hot-key-ms":               100,
							"ignore-expunges":          false,
							"ignored-bins":             "tip,wip",
							"ignored-sets":             "zip,zap",
							"max-throughput":           100000,
							"remote-namespace":         "null",
							"sc-replication-wait-ms":   100,
							"ship-bin-luts":            false,
							"ship-nsup-deletes":        false,
							"ship-only-specified-sets": false,
							"shipped-bins":             "",
							"shipped-sets":             "",
							"transaction-queue-limit":  16384,
							"write-policy":             "auto",
						},
					},
					"node-address-port":            "",
					"period-ms":                    100,
					"tls-name":                     "null",
					"use-alternate-access-address": false,
				},
			},
			"src-id":       1,
			"trace-sample": 0,
		},
	},
	Conf{"metadata": Conf{"asd_build": "6.4.0.0", "node_id": "BB9030011AC4202"}},
	Conf{
		"xdr": Conf{
			"dcs": []Conf{
				{
					"name": "DC1",
					"namespaces": []Conf{
						{
							"name":       "test",
							"bin-policy": "changed-or-specified",
							"ship-bins":  []string{"foo", "bar"},
							"ship-sets":  []string{"blah", "blee"},
						},
					},
				},
				{
					"name": "DC2",
					"namespaces": []Conf{
						{
							"name":        "bar",
							"ignore-bins": []string{"tip", "wip"},
							"ignore-sets": []string{"zip", "zap"},
						},
					},
				},
			},
			"src-id": 1,
		},
	},
}

var shadowDeviceIssueTC = GenerateTC{
	"Shadow Device Issue",
	false, // removeDefaults
	Conf{ // allConfigs
		"namespaces": Conf{
			"wi-pzn": Conf{
				"replication-factor":                        2,
				"stop-writes-sys-memory-pct":                90,
				"default-ttl":                               0,
				"nsup-period":                               120,
				"rack-id":                                   1,
				"storage-engine":                            "device",
				"storage-engine.flush-size":                 524288,    // 512K
				"storage-engine.max-write-cache":            536870912, // 512M
				"storage-engine.sindex-startup-device-scan": true,
				"storage-engine.file[0]":                    "/dev/DATA1PART1",
				"storage-engine.file[0].shadow":             "/dev/DATA2PART1",
				"storage-engine.file[1]":                    "/dev/DATA1PART2",
				"storage-engine.file[1].shadow":             "/dev/DATA2PART2",
				"storage-engine.file[2]":                    "/dev/DATA1PART3",
				"storage-engine.file[2].shadow":             "/dev/DATA2PART3",
				"storage-engine.file[3]":                    "/dev/DATA1PART4",
				"storage-engine.file[3].shadow":             "/dev/DATA2PART4",
				"storage-engine.file[4]":                    "/dev/DATA1PART5",
				"storage-engine.file[4].shadow":             "/dev/DATA2PART5",
				"storage-engine.file[5]":                    "/dev/DATA1PART6",
				"storage-engine.file[5].shadow":             "/dev/DATA2PART6",
				"storage-engine.file[6]":                    "/dev/DATA1PART7",
				"storage-engine.file[6].shadow":             "/dev/DATA2PART7",
				"storage-engine.file[7]":                    "/dev/DATA1PART8",
				"storage-engine.file[7].shadow":             "/dev/DATA2PART8",
				"storage-engine.file[8]":                    "/dev/DATA1PART23",
				"storage-engine.file[8].shadow":             "/dev/DATA2PART23",
				"storage-engine.file[9]":                    "/dev/DATA1PART24",
				"storage-engine.file[9].shadow":             "/dev/DATA2PART24",
				"storage-engine.file[10]":                   "/dev/DATA1PART25",
				"storage-engine.file[10].shadow":            "/dev/DATA2PART25",
				"storage-engine.file[11]":                   "/dev/DATA1PART32",
				"storage-engine.file[11].shadow":            "/dev/DATA2PART32",
				"sets": Conf{
					"pzn-audience-metadata": Conf{
						"enable-index": true,
					},
				},
			},
		},
	},
	Conf{"metadata": Conf{"asd_build": "8.0.0.0", "node_id": "BB9030011AC4202"}}, // metadata
	Conf{ // expected
		"namespaces": []Conf{
			{
				"name":                       "wi-pzn",
				"replication-factor":         2,
				"stop-writes-sys-memory-pct": 90,
				"default-ttl":                0,
				"nsup-period":                120,
				"rack-id":                    1,
				"storage-engine": Conf{
					"type":                       "device",
					"flush-size":                 524288,
					"max-write-cache":            536870912,
					"sindex-startup-device-scan": true,
					"files": []string{
						"/dev/DATA1PART1 /dev/DATA2PART1",
						"/dev/DATA1PART2 /dev/DATA2PART2",
						"/dev/DATA1PART3 /dev/DATA2PART3",
						"/dev/DATA1PART4 /dev/DATA2PART4",
						"/dev/DATA1PART5 /dev/DATA2PART5",
						"/dev/DATA1PART6 /dev/DATA2PART6",
						"/dev/DATA1PART7 /dev/DATA2PART7",
						"/dev/DATA1PART8 /dev/DATA2PART8",
						"/dev/DATA1PART23 /dev/DATA2PART23",
						"/dev/DATA1PART24 /dev/DATA2PART24",
						"/dev/DATA1PART25 /dev/DATA2PART25",
						"/dev/DATA1PART32 /dev/DATA2PART32",
					},
				},
				"sets": []Conf{
					{
						"name":         "pzn-audience-metadata",
						"enable-index": true,
					},
				},
			},
		},
	},
}
