package accesscontrol

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AerospikeAccessControlSpec) DeepCopyInto(out *AerospikeAccessControlSpec) {
	*out = *in
	if in.AdminPolicy != nil {
		in, out := &in.AdminPolicy, &out.AdminPolicy
		*out = new(AerospikeClientAdminPolicy)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]AerospikeRoleSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]AerospikeUserSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AerospikeAccessControlSpec.
func (in *AerospikeAccessControlSpec) DeepCopy() *AerospikeAccessControlSpec {
	if in == nil {
		return nil
	}
	out := new(AerospikeAccessControlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AerospikeRoleSpec) DeepCopyInto(out *AerospikeRoleSpec) {
	*out = *in
	if in.Privileges != nil {
		in, out := &in.Privileges, &out.Privileges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Whitelist != nil {
		in, out := &in.Whitelist, &out.Whitelist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AerospikeRoleSpec.
func (in *AerospikeRoleSpec) DeepCopy() *AerospikeRoleSpec {
	if in == nil {
		return nil
	}
	out := new(AerospikeRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AerospikeUserSpec) DeepCopyInto(out *AerospikeUserSpec) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AerospikeUserSpec.
func (in *AerospikeUserSpec) DeepCopy() *AerospikeUserSpec {
	if in == nil {
		return nil
	}
	out := new(AerospikeUserSpec)
	in.DeepCopyInto(out)
	return out
}
